### ISSUE TITLE
Build error on v5.7 (OS X 10.12.3, Xcode 8.2.1)

### ISSUE THREAD

**Issue by alexreg** [arqbackup/arq_restore#35] opened 2017-02-06 01:06 UTC
https://gist.github.com/76219f9acafc6624f529faa86ab65dad

What's going on here?

**Comment by arqbackup** [comment] 2017-05-29 12:37
Closing this issue because alexreg isn't responding with more information.

**Closed by arqbackup** 2017-05-29 12:37 UTC

**Comment by alexreg** [comment] 2017-05-29 12:44
You didn't ask for more info?

**Comment by arqbackup** [comment] 2017-05-29 12:45
I commented on your gist Feb 6: https://gist.github.com/anonymous/76219f9acafc6624f529faa86ab65dad

**Comment by alexreg** [comment] 2017-05-29 14:45
Ah, okay.

> What command did you use to produce this output?

`xcodebuild -configuration Release`

**Comment by arqbackup** [comment] 2017-05-29 16:37
OK. Don't know why you're getting that. I don't get an error when I compile it that way. Maybe something changed in the intervening 3 months.

**Comment by alexreg** [comment] 2017-05-29 16:52
Nope. It still happens now... same error.

**Comment by arqbackup** [comment] 2017-05-29 17:03
I have MacOS 10.12.5 and Xcode 8.3.2.
Doesn't happen for me, so I don't know how to reproduce it.
This is the output for 'clean' and then build:

https://gist.github.com/arqbackup/fac1800e16c1a0f3fcaffdd89aa4f8f9

**Comment by alexreg** [comment] 2017-05-29 17:22
Well, can't you debug it from the error message? Anyway, what environmental configuration are you doing before running those commands, if any at all?

**Comment by arqbackup** [comment] 2017-05-29 17:34
I don't understand the error message you get. It says the header file can't be found, but the header file exists. I don't set any special environment variables. Looks like you reset HEADER_SEARCH_PATHS and LIBRARY_SEARCH_PATHS though, overriding the values in the Xcode project. Maybe stop doing that.

**Comment by alexreg** [comment] 2017-05-29 17:50
Yeah... if I don't set those environment variables, I get these errors however.

https://gist.github.com/d49f557fed13b6be6aee9e079d93b1ae

**Comment by arqbackup** [comment] 2017-05-29 18:15
Have you looked at the Xcode project at all? It expects the OpenSSL library in /usr/local/ssl.

**Comment by alexreg** [comment] 2017-05-29 19:21
Ah. Well, I don't have anything there. That directory doesn't exist, and indeed it's non-standard. Homebrew installs the library to to `/usr/local/opt/openssl`. I think you may want to allow for a configurable path, or just use pkgconfig.
